spring:
  security:
    oauth2:
      # OAuth2 ?????
      client:
        # ??????
        registration:
          # OAuth2 ?????????????????
          github:
            # ??????ID
            client-id: dcdb1b4a074a8edcb366
            # ????????
            client-secret: d08c4c4c52fe5de82569b14064dd57cc522d8f78
          gitee:
            # ??????ID
            client-id: d509b4d2785d5a03dada66d14408a55a037d924337a1fb77374835db6d584773
            # ????????
            client-secret: a65b4ef3e434eed950b25c959d572df897b5ec517efe82d9d27fe6c4573819f3
#             ???????? authorization_code????????AuthorizationGrantType
            authorization-grant-type: authorization_code
            # ??????????
            redirect-uri: http://localhost:8080/login/oauth2/code/gitee
            # ???????????????????
            scope:
              - user_info # ??????
        provider:
          gitee:
            # ??????
            authorization-uri: https://gitee.com/oauth/authorize
            # ????????
            token-uri: https://gitee.com/oauth/token
            # ????????
            user-info-uri: https://gitee.com/api/v5/user
            # ?????????????
            user-name-attribute: login