spring:
  security:
    user:
      name: admin
      password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password:
  session:
    redis:
      # ????
      namespace: spring:security