spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true
      metrics:
        enabled: true
  application:
    name: auth-cloud-gateway
server:
  port: 80
