spring:
  security:
    user:
      name: admin
      password: 123456
server:
  servlet:
    session:
      timeout: 3600s
      cookie:
        # ??? HTTP???????????
        http-only: true
        # ??? HTTPS ????
        secure: true
