spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_security?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 12345678
  security:
    oauth2:
      # OAuth2 客户端配置
      client:
        # 基础属性前缀
        registration:
          # OAuth2服务提供商标识符（由当前项目定义）
          github:
            # 申请的客户端ID
            client-id: dcdb1b4a074a8edcb366
            # 申请的客户端密码
            client-secret: d08c4c4c52fe5de82569b14064dd57cc522d8f78
          gitee:
            client-name: 码云登录
            # 申请的客户端ID
            client-id: d509b4d2785d5a03dada66d14408a55a037d924337a1fb77374835db6d584773
            # 申请的客户端密码
            client-secret: a65b4ef3e434eed950b25c959d572df897b5ec517efe82d9d27fe6c4573819f3
            # 授权模式，固定为 authorization_code，其他值可以参考AuthorizationGrantType
            authorization-grant-type: authorization_code
            # 回调地址，接收授权码
            redirect-uri: http://localhost:8080/login/oauth2/code/gitee
            # 权限范围，可配置项在码云应用信息中查看
            scope:
              - user_info # 个人用户信息
        provider:
          gitee:
            # 申请授权地址
            authorization-uri: https://gitee.com/oauth/authorize
            # 获取访问令牌地址
            token-uri: https://gitee.com/oauth/token
            # 查询用户信息地址
            user-info-uri: https://gitee.com/api/v5/user
            # 码云用户信息中的用户名字段
            # user-name-attribute: login
            # 码云用户信息中的用户ID字段
            user-name-attribute: id
